School/Home/urls.py
from django.urls import path
from Home import views
from django.views.generic import TemplateView 

app_name ="Home"

urlpatterns = [ 

    path('notice/',views.Home,name='home'),
   # path('notice/<int:pk>',views.NoticeDetail.as_view(),name='notice_detail'),
    # path('notice/delete/<int:pk>',views.NoticeDelete.as_view(),name='notice_delete'),
    path('notice/add/',views.NoticeAdd,name='notice_add'),
    path('accounts/login/',views.USER_LOGIN,name='login'),
    path('test/',views.AddUser,name='test'),
    path("logout/",views.user_logout,name='logout'),
    path('notice/update/<int:notice_id>',views.update_notice,name='update_notice'),
    path('notice/detail/<int:notice_id>',views.notice_detail,name='notice_detail'),
    path('notice/delete/<int:notice_id>',views.delete_notice,name='delete_notice'),
    path('search/',views.search,name='search'),
]

School/School/urls.py
from django.contrib import admin
from django.urls import path,include
from . import settings
from django.conf.urls.static import static

urlpatterns = [
    path('',include('Home.urls')),
    path('',include('UserProfile.urls')),
    path('admin/', admin.site.urls),
]+static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)

School/UserProfile/urls.py
from django.urls import path
from . import views
urlpatterns= [
    path('profile/', views.Profile, name='profile'),
]

School/Home/models.py
from django.db import models
from django.contrib.auth.models import User

class Notice(models.Model):
    user = models.ForeignKey(User,on_delete=models.CASCADE)
    date_uploaded = models.DateTimeField(auto_now_add=True)
    Topic = models.CharField(max_length=100)
    News = models.TextField()
    image = models.ImageField(upload_to='News',blank=True)

    class Mete:
        vartbose_name = 'News'

    def __str__(self):
        return self.Topic
    
    

School/UserProfile/models.py
from django.db import models
from django.contrib.auth.models import User


class Admin(models.Model):
    user = models.OneToOneField(User,on_delete=models.CASCADE)
    admin_name = models.CharField(max_length=100)
    admin_email = models.EmailField()
    admin_password = models.CharField(max_length=100)
    admin_phone = models.CharField(max_length=10)

    def __str__(self):
        return self.admin_name
    

class UserAccount(models.Model):
    user_name = models.CharField(max_length=100)
    user_email = models.EmailField()
    user_password = models.CharField(max_length=100)
    user_phone = models.CharField(max_length=10)
    user_address = models.TextField()
    user_dob = models.DateField()
    user_profile_pic = models.ImageField(upload_to='UserProfile/ProfilePic/',blank=True)

    def __str__(self):
        return self.user_name

    class Meta:
        verbose_name_plural = 'User Account'

class UserProfile(models.Model):
    user_account = models.OneToOneField(UserAccount,on_delete=models.CASCADE)
    user_bio = models.TextField(max_length=99)
    profile_created_at = models.DateTimeField(auto_now_add=True)
    profile_updated_at = models.DateTimeField(auto_now=True)
    user_nick_name = models.CharField(max_length=20,default= 'User')

    def __str__(self):
        time = str(self.profile_updated_at)
        return self.user_nick_name + '`s Profile ' + time

class School_class(models.Model):
    students = models.ManyToManyField(UserAccount)
    class_name = models.CharField(max_length=20)
    class_teacher= models.CharField(max_length=20)
    class_number = models.IntegerField()

    class Meta:
        verbose_name_plural = 'School Class'


    def __str__(self):
        return "class => " + self.class_name+ " | Room Number = > " + str(self.class_number)   

School/Home/forms.py
from django import forms


class StudentFrom(forms.Form):
    user_name = forms.CharField(max_length=100 , label="Student Name = > ")
    user_pass = forms.CharField(widget=forms.PasswordInput())

School/Home/views.py
from django.shortcuts import render,redirect
from django.http import HttpResponse
from . import models
from django.views.generic import TemplateView , ListView ,CreateView, DetailView ,DeleteView
from django.urls import reverse_lazy
from . import models
from django.contrib.auth.models import User
from django.contrib.auth import authenticate,login,logout
from django.contrib.auth.decorators import login_required



def Home(request):
    search_keyword = request.session.get('search', '')
    if search_keyword:
        search_keyword = search_keyword.strip()
        notice = models.Notice.objects.filter(Topic__icontains=search_keyword).filter(user=request.user)
        context =  {
            'Notices':notice,
            'user':request.user
        }
        request.session['search'] = ""
        
    else:
        notice = models.Notice.objects.filter(user=request.user)
        context =  {
            'Notices':notice,
            'user':request.user
        }
    return render(request,'Home/home.html',context)

class NoticeDetail(DetailView):
    template_name = 'Home/noticeDetail.html'
    context_object_name = 'Notice'
    model = models.Notice






@login_required
def NoticeAdd(request):
    if request.method == "POST":
        data_topic = request.POST.get("topic_name")
        data_news = request.POST.get("news")
        data = models.Notice(user=request.user,Topic=data_topic,News=data_news)
        data.save()
        return redirect('Home:home')
    
    else:
        return render(request,'Home/notice_form.html')





def USER_LOGIN(request):
    if request.method == "POST":
        user_name = request.POST.get("user_name")
        user_pass = request.POST.get("user_pass")
        user = authenticate(request,username=user_name,password=user_pass)
        if user is not None:
            login(request,user)
            return redirect('Home:home')
        
    else:
        return render(request,'Home/login.html')
    
@login_required
def AddUser(request):
    if request.method == "POST":
        user_name = request.POST.get("user_name")
        user_pass = request.POST.get("user_pass")
        user = User.objects.create_user(username=user_name,password=user_pass)
        user.save()
        return redirect('Home:login')
    else:
        return render(request,'Home/base.html')
    

@login_required
def user_logout(request):
    logout(request)
    return redirect('Home:login')

@login_required
def update_notice(request,notice_id):
    if request.method == "POST":
        id = request.POST.get('notice_id')
        updated_topic = request.POST.get('topic_name')
        updated_news = request.POST.get('news')
        data = models.Notice.objects.get(id=id)
        data.Topic = updated_topic
        data.News = updated_news
        data.save()
        return redirect('Home:home')

    else:
        data = models.Notice.objects.get(id=notice_id)
        context = {
            'Notice':data
        }
        return render(request,'Home/update.html',context)
    
@login_required
def notice_detail(request,notice_id):
    if request.method =="POST":
        pass
    else:
        data = models.Notice.objects.get(id=notice_id)
        context = {
            'Notice':data
        }
        return render(request,'Home/detail.html',context)

@login_required
def delete_notice(request,notice_id):
    data = models.Notice.objects.get(id=notice_id)
    data.delete()
    return redirect('Home:home')


@login_required
def search(request):
    request.session['search'] = request.GET.get('search_keyword')
    return redirect('Home:home')

School/UserProfile/views.py
from django.shortcuts import render
from django.http import HttpResponse

def Profile(request):
    return HttpResponse('Profile Page')

School/Home/templates/Home/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'Home/css/login.css' %}">
    <title>Login</title>
</head>
<body>


    <div class="logo">   

    </div>

    <div class = "header">
        <h1>SHREE RASTRIYA MAVI SECONDARY COLLAGE</h1> <br>
        <h2>It is a leading government institution, providing education from PG to grade 12 and DCE & pre-DCE.</h2>
        
    </div>
    
    <div class="login">
    
        

        <form method="post" action="#">
            {% csrf_token %}
            <div class="credientials">
                <input class="ced" type="text" placeholder="User-name or Email"  name= "user_name"required> <br>
                <div class="gap"></div>
                <input class="ced" type="password" placeholder="Password" name= "user_pass" required> <br>
                <input class="log-in" type="submit" value="Log In"><br>
                <a href="#" class="pass">Forgot password?</a><br>
                <input class="creat-acc" type="submit" value="Register account">
            </div>

        </form>
    </div>
</body>
</html>

School/Home/templates/Home/detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title> Topic</title>
</head>
<body>
        <h1> Topic = > {{Notice.Topic}}</h1>
    <!-- date_uploaded = models.DateTimeField(auto_now_add=True) -->
            <h2> UPloaded date = > {{Notice.date_uploaded}}</h2>
        <p> News = >  {{Notice.News}}</p>
        <a href="{% url 'Home:update_notice' Notice.id %}"> Change Notice </a> <br>
        <a href="{% url 'Home:home'  %}"> back </a> <br>

        <a href="{% url 'Home:delete_notice' Notice.id %}"> Delete Notice </a>

</body>
</html>

School/Home/templates/Home/home.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title> Home </title>
</head>
<body>
    {{user}}
    {% if Notices%}
        <form action="{% url 'Home:search' %}">
            {% csrf_token %}
            <input type="text" name="search_keyword" placeholder="Search">
            <input type="submit" value="search">
        </form>

     {% for Notic in Notices%}
         <ul>
         <li>  {{Notic.Topic}} id = > {{Notic.id}}</li>
         <a href="{% url 'Home:notice_detail' Notic.id %}"> View More </a>

         </ul>
     {% endfor %}
    {% else %}
        <h1> No Notices Found </h1>
        <a href="{% url 'Home:notice_add' %}"> Add Notice </a>
    {% endif %}

    <a href="{% url 'Home:logout' %}"> logout </a> <br>
    
    <a href="{% url 'Home:notice_add' %}"> Add Notice </a>

</body>
</html>

School/Home/templates/Home/login.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static 'Home/css/login.css' %}">
    <title>Login</title>
</head>
<body>


    <div class="logo">   

    </div>

    <div class = "header">
        <h1>SHREE RASTRIYA MAVI SECONDARY COLLAGE</h1> <br>
        <h2>It is a leading government institution, providing education from PG to grade 12 and DCE & pre-DCE.</h2>
        
    </div>
    
    <div class="login">
    
        

        <form method="post" action="#">
            {% csrf_token %}
            <div class="credientials">
                <input class="ced" type="text" placeholder="User-name or Email"  name= "user_name"required> <br>
                <div class="gap"></div>
                <input class="ced" type="password" placeholder="Password" name= "user_pass" required> <br>
                <input class="log-in" type="submit" value="Log In"><br>
                <a href="#" class="pass">Forgot password?</a><br>
                <input class="creat-acc" type="submit" value="Register account">
            </div>

        </form>
    </div>
</body>
</html>

School/Home/templates/Home/logout.html
<form method="post">
    {% csrf_token %}
    <input type="submit" value="Logout">
</form>

School/Home/templates/Home/noticeDetail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Notice - View </title>
</head>
<body>
    <h1> Notice about = > {{Notice.Topic}}</h1>
        <p> {{Notice.News}} </p>
     <h4> Date: {{Notice.date_uploaded}} </h4>   
</body>
</html>

School/Home/templates/Home/notice_confirm_delete.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title> Delete ? </title>
</head>
<body>
        <form method="post">
            {% csrf_token %}
            {{form}}
           <h1> Are You sure you want to DELETE ! {{Notice.Topic}} ? </h1>
            <input type="submit" value="Delete">

        </form>    
</body>
</html>

School/Home/templates/Home/notice_form.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>ADD Notice </title>
</head>
<body>
    <form method="post">
        {% csrf_token %}
        <input type="text" placeholder=" Topic name " name="topic_name" required> <br>
        <input type="text" placeholder=" News ! " name="news" required> <br>
        <!-- <input type="image" placeholder= " Image" name = image > <br> -->

        <input type="submit" value="Add Notice">
     </form>   

</body>
</html>

School/Home/templates/Home/test.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Test</title>
</head>
<body>
        <form method="post" action="" > 
            {% csrf_token %}
            {{form}}
            <input type="submit" value="Submit">
        </form> 
</body>
</html>

School/Home/templates/Home/update.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>update Notice </title>
</head>
<body>
    <form method="post">
        {% csrf_token %}
        <input type="hidden" name="notice_id" value="{{Notice.id}}">
        
        <input type="text" placeholder="{{Notice.Topic}}" name="topic_name" required> <br>
        <input type="text" placeholder="{{Notice.News}}" name="news" required> <br>
        <!-- <input type="image" placeholder= " Image" name = image > <br> -->

        <input type="submit" value="Add Notice">
     </form>   

</body>
</html>